version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.17.0

    steps:
      - checkout
      - run: npm install
      - run:
        command: npm start
        background: true
      - run: npm test