# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.0

    working_directory: ~/repo

    steps:
      - run: npm install
      - run: npm jest
